version: '3'

networks:
  web_net:
    external: true

services:
  vueui:
    container_name: vueui
    image: yuanjunjie/foundation:dev
    restart: always
    networks:
      - web_net:
    ports:
      - '8080:80'
