version: '3'

networks:
  nginx_net:
    external:
      name: web_net

services:
  vueui:
    container_name: vueui
    image: yuanjunjie/foundation:dev
    restart: always
    networks:
      - web_net
    ports:
      - '8080:80'
