version: '3'

networks:
  nginx_net:
    external:
      name: web_net

services:
  vueui:
    container_name: vueui
    image: yuanjunjie/foundation:dev
    restart: always
    networks:
      nginx_net:
      ipv4_address: 172.32.0.4
    ports:
      - '8080:80'
