name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: fd-dev

    steps:
      - uses: actions/checkout@v2

      - name: Run Pull
        run: |
          sudo su
          docker build -t yunjunjie/foundation:dev ./
          docker run yunjunjie/foundation:dev
