name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker
        run: |
          docker build -t yuanjunjie/foundation:dev .

      - name: Login to Docker Registry
        run: docker login --username=${{ secrets.DOCKER_USER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Registry
        run: |
          docker push yuanjunjie/foundation:dev

  deploy:
    needs: [build]
    name: Deploy
    runs-on: fd-dev

    steps:
      - uses: actions/checkout@v2

      - name: Update docker images
        run: |
          sudo su
          docker pull yuanjunjie/foundation:dev

      - name: Login to Docker Registry
        run: |
          sudo su
          sudo docker login --username=${{ secrets.DOCKER_USER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Run
        run: |
          sudo su
          ls 
          sudo docker compose -f docker-compose.yml up -d
