name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          pwd
          ls
          docker build -t yuanjunjie/foundation:dev -f work/foundation/foundation/Dockerfile .

      - name: Login to Registry
        run: docker login --username=yuanjunjie --password yjj541823.0.

      - name: Push
        run: |
          docker push yuanjunjie/nginx:dev

  deploy:
    needs: [build]
    name: Deploy
    runs-on: fd-dev

    steps:
      - uses: actions/checkout@v2

      - name: run
        run: docker run yuanjunjie/foundation:dev
