name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Install npm dependencies
        run:  npm install 
      - name: Run build task
        run:  npm run build 
      # upload
      - name: build app  
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.DR_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: dist # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: ${{ secrets.DR_HOST }} # 你的阿里云公网地址
          REMOTE_USER: ${{ secrets.DR_USER }} # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: ${{ secrets.DR_REMOTE_PATH }} # 打包后的 dist 文件夹将放在 /root/node-server
            
            
          
